apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"mutation1","example-webhook-enabled":"true"},"name":"mutation-deployment-test","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"mutation1"}},"template":{"metadata":{"labels":{"app":"mutation1","example-webhook-enabled":"true"}},"spec":{"containers":[{"command":["/bin/bash"],"image":"trohit7/mutation:update","name":"mutation1","ports":[{"containerPort":8080}],"tty":true}]}}}}
  creationTimestamp: "2024-01-18T11:42:18Z"
  labels:
    app: mutation1
    author: minikube-user
    example-webhook-enabled: "true"
    operation: CREATE
  name: mutation-deployment-test
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mutation1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mutation1
        example-webhook-enabled: "true"
    spec:
      containers:
      - command:
        - /bin/bash
        image: trohit7/mutation:update
        imagePullPolicy: IfNotPresent
        name: mutation1
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
