apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-01-18T19:23:59Z"
  generateName: mutation-deployment-test2-8484c4598c-
  labels:
    app: mutation2
    author: system_serviceaccount_kube-system_replicaset-controller
    example-webhook-enabled: "true"
    operation: CREATE
    pod-template-hash: 8484c4598c
  name: mutation-deployment-test2-8484c4598c-lvhlr
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: mutation-deployment-test2-8484c4598c
    uid: afc8ec18-fc42-4805-bbb0-3f49f423d084
spec:
  containers:
  - command:
    - /bin/bash
    image: trohit7/mutation:update
    imagePullPolicy: IfNotPresent
    name: mutation2
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fsvkd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-fsvkd
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
